NURFED_MENUS["General"] = {
	template = "nrf_options",
	children = {
		scroll = {
			template = "nrf_scroll",
			vars = { pages = 2 },
		},
		check1 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", 3, -3 },
			vars = { text = NRF_AUTOREPAIR, option = "repair", page = 1 },
		},
		check2 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck1", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_PINGWARNING, option = "ping", page = 1 },
		},
		check3 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck2", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_UNTRAINABLE, option = "traineravailable", page = 1 },
		},
		check4 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck3", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_CHATTIMESTAMPS, option = "timestamps", page = 1 },
		},
		check5 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck4", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_RAIDGROUP, option = "raidgroup", page = 1 },
		},
		check6 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck5", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_RAIDCLASS, option = "raidclass", page = 1 },
		},
		check7 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck6", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_CHATBUTTONS, option = "chatbuttons", func = function() nrf_togglechat() end, page = 1 },
		},
		check8 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck7", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_CHATPREFIX, option = "chatprefix", page = 1 },
		},
		check9 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck8", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_AUTOINVITE, option = "autoinvite", page = 1 },
		},
		check10 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck9", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Invite Reply", option = "invitetext", page = 1 },
		},
		check11 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck10", "BOTTOMLEFT", 0, -2 },
			vars = { text = NRF_CHATFADE, option = "chatfade", func = function() nrf_togglechat() end, page = 1 },
		},
		check12 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck11", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Square Minimap", option = "squareminimap", page = 1 },
		},
		check13 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck17", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Aura Cooldowns", option = "cdaura", page = 1 },
		},

		slider1 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parent", "TOPRIGHT", -23, -15 },
			vars = {
				text = NRF_REPAIRLIMIT,
				option = "repairlimit",
				low = 0,
				high = 200,
				min = 0,
				max = 200,
				step = 1,
				format = "%.0f",
				right = true,
				page = 1,
			},
		},
		slider2 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parentslider1", "BOTTOMRIGHT", 0, -25 },
			vars = {
				text = NRF_CHATFADETIME,
				option = "chatfadetime",
				low = 0,
				high = 250,
				min = 0,
				max = 250,
				step = 1,
				format = "%.0f",
				right = true,
				func = function() nrf_togglechat() end,
				page = 1,
			},
		},
		input1 = {
			template = "nrf_editbox",
			Anchor = { "TOPRIGHT", "$parentslider2", "BOTTOMRIGHT", 0, -20 },
			vars = { text = NRF_TIMESTAMP, option = "timestampsformat", page = 1 },
		},
		input2 = {
			template = "nrf_editbox",
			Anchor = { "TOPRIGHT", "$parentinput1", "BOTTOMRIGHT", 0, -15 },
			vars = { text = NRF_KEYWORD, option = "keyword", page = 1 },
		},
		check14 = {
			template = "nrf_check",
			Anchor = { "TOPRIGHT", "$parentinput2", "BOTTOMRIGHT", 0, -15 },
			vars = { text = "Disable Casting Bar", option = "hidecasting", right = true, func = function() nrf_togglcast() end, page = 1 },
		},
		check15 = {
			template = "nrf_check",
			Anchor = { "TOPRIGHT", "$parentcheck14", "BOTTOMRIGHT", 0, -2 },
			vars = { text = "Show Action Tooltips", option = "tooltips", right = true, page = 1 },
		},
		check16 = {
			template = "nrf_check",
			Anchor = { "TOPRIGHT", "$parentcheck15", "BOTTOMRIGHT", 0, -2 },
			vars = { text = "Fade In Actions", option = "fadein", right = true, page = 1 },
		},
		check17 = {
			template = "nrf_check",
			Anchor = { "TOPRIGHT", "$parentcheck16", "BOTTOMRIGHT", 0, -2 },
			vars = { text = "Hide Main Bar", option = "hidemain", right = true, func = function() nrf_mainmenu() end, page = 1 },
		},

		check18 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parent", "TOPLEFT", 3, -3 },
			vars = { text = "Show Bags", option = "bagsshow", func = function() nrf_updatemainbar("bags") end, page = 2 },
		},
		check19 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck18", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Vertical Bags", option = "bagsvert", func = function() nrf_updatemainbar("bags") end, page = 2 },
		},
		check20 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck19", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Show Micro", option = "microshow", func = function() nrf_updatemainbar("micro") end, page = 2 },
		},
		check21 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck20", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Show Stance", option = "stanceshow", func = function() nrf_updatemainbar("stance") end, page = 2 },
		},
		check22 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck21", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Vertical Stance", option = "stancevert", func = function() nrf_updatemainbar("stance") end, page = 2 },
		},
		check23 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck22", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Show Pet Bar", option = "petbarshow", func = function() nrf_updatemainbar("petbar") end, page = 2 },
		},
		check24 = {
			template = "nrf_check",
			Anchor = { "TOPLEFT", "$parentcheck23", "BOTTOMLEFT", 0, -2 },
			vars = { text = "Vertical Pet Bar", option = "petbarvert", func = function() nrf_updatemainbar("petbar") end, page = 2 },
		},

		slider3 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parent", "TOPRIGHT", -23, -15 },
			vars = {
				text = "Bags Scale",
				option = "bagsscale",
				low = "25%",
				high = "100%",
				min = 0.25,
				max = 1,
				step = 0.01,
				deci = 2,
				format = "%.2f",
				right = true,
				func = function() nrf_updatemainbar("bags") end,
				page = 2,
			},
		},
		slider4 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parentslider3", "BOTTOMRIGHT", 0, -25 },
			vars = {
				text = "Micro Scale",
				option = "microscale",
				low = "25%",
				high = "100%",
				min = 0.25,
				max = 1,
				step = 0.01,
				deci = 2,
				format = "%.2f",
				right = true,
				func = function() nrf_updatemainbar("micro") end,
				page = 2,
			},
		},
		slider5 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parentslider4", "BOTTOMRIGHT", 0, -25 },
			vars = {
				text = "Stance Scale",
				option = "stancescale",
				low = "25%",
				high = "100%",
				min = 0.25,
				max = 1,
				step = 0.01,
				deci = 2,
				format = "%.2f",
				right = true,
				func = function() nrf_updatemainbar("stance") end,
				page = 2,
			},
		},
		slider6 = {
			template = "nrf_slider",
			Anchor = { "TOPRIGHT", "$parentslider5", "BOTTOMRIGHT", 0, -25 },
			vars = {
				text = "Pet Bar Scale",
				option = "petbarscale",
				low = "25%",
				high = "100%",
				min = 0.25,
				max = 1,
				step = 0.01,
				deci = 2,
				format = "%.2f",
				right = true,
				func = function() nrf_updatemainbar("petbar") end,
				page = 2,
			},
		},
	},
}